dawsonjon/PicoRX

- ui.cpp
It bizarrely led to an extra entry of "50Hz" as an option :) 
Must be how the strings got laid out in the image.
> Fix off by 1 error in squelch menu items

- ssd1306.c
- ssd1306.h
- ui.cpp
fix compiler warning/error on ssd1306_deinit
also used a 2nd pointer to clean up some of the repeated "-1" in the show function
I then went on to another fix for oled writing:
This time we allocate 129 bytes per page to make room for the 0x40 at the start of each I2C transmission
> 2 "fixes" for the oled compiler error

- .github/workflows/build.yml
Might be good to have it for additional cross-validation and making releases. Removing the `build` directory from the repo might now make sense.
> Added basic GitHub actions script

- picorx.cpp
- rx.cpp
- rx.h
I know that some people are not huge fans of using const LUTs, but saves some memory and often compute.
Also added few small fixes/adjustments. time_us_32() overflows after more than an hour, so is enough for measuring momentary utilization.
> Some adjustments around FFT calculation + minor fixes

- .gitignore
- ssd1306.c
- ssd1306.h
- ui.cpp
- ui.h
s/display_print/display_print_str/ and s/display_write/display_print_char/
display_print_char, display_print_num, display_print_str:
- added a style bitfield. style_reversed style_centered so far
display_print_str:
supports \n for new line
supperts \a to toggle text reverse font
fixed out by 1 error in PSU mode menu
added vim backup files to gitignore
> Menus now use double size font

- ui.cpp
- ui.h
recall menu
- prints frequency in 2X
- prints name in 2X if it'll fit, else 1x
- now skips blank entries when browsing through
- remembers which memory you last selected if you use the menu button
-- if you press the encoder, it sets last memory to 000
Store menu
- redesigned with 2X font for station name
- 
Show memory upload progress by inverting the display colours
Consolidated USB upload menus into one
reworked print_menu_option.
- use strtok to split the options#list#
- if only 2 options and they'd fit, print them both with highlight
added display_print_freq()
Added style_nowrap. extra characters just get ignored
Added style_right to print stuff to..... the right
Added (harmless) missing trailing # on a couple of enumerate_entry calls
> recall menu and other UI tweaks

- CMakeLists.txt
- debouncer.c
- debouncer.h
- event.c
- event.h
- picorx.cpp
- ui.cpp
- ui.h
This PR is a first step towards more reactive design. In current design, due to blocking waits scattered throughout `ui.cpp`, there was noticeable jitter and button presses were missed fairly often.
Next steps:
- move encoder handling to the same timer as other switches
- eliminate `event_get` calls, as ideally there should be only one, top-level call to this function and the events should be propagated from this point. Requires significant `ui.cpp` changes (introducing explicit `ui_state` variable, eliminating all infinite while loops, moving to a more data-driven menu design).
> Improving IO handling

- debouncer.h
- ui.cpp
string_entry() : tweaked scrolling and added visual scroll bar
vscode doesnt like uint
bounds check in print_enum_option.
If parameter is outside range:
With 2 options dont highlight anything either option
With >2 options highlight the 1st
> small fixes plus tweaked scrolling in string_entry()

- ui.cpp
- ui.h
Fix immediate lockup after upload that occured 90% of the time.
Oddly a usb remove insert didnt exihibit this.
Took ages to track down, but min_r was -inf so the loop never iterated
migrate more ssd1306_ calls to display_
> fix lockup and cleaning

- ssd1306.c
- ssd1306.h
- ui.cpp
Shift the display memory horizontally and/or vertically. Supports positive and vertical.
The displaybuffer is edited in place - zeros get shifted in, it does not wrap the data.
update_display5 dances around with a lissajous pattern as a test. but it looks pretty so ive left it in :) (for now?)
> ssd1306_scroll_screen(&disp, uint x, uint y );

- ui.cpp
- ui.h
Added signal strength to Recall page
Waterfall uses display scrolling and just paints the new row.
tidying:
factored out int ui::dBm_to_S(float power_dBm);
factored out draw_slim_status(uint16_t y, rx_status & status, rx & receiver);
renderpage_* now know if they've just been switched to (so the can reinit if required)
s/recall/memory_recall/
s/store/memory_store/
s/update_display/renderpage_original/
s/update_display2/renderpage_bigspectrum/
s/update_display3/renderpage_waterfall/
s/update_display4/renderpage_bigtext/
s/update_display5/renderpage_fun/
> Recall shows signal strength & tidying (take 2)

- ui.cpp
- ui.h
top level menu no longer quits to home after an action so you can edit multiple things or just not get frustrated when you accidentally hit back.
and exiting hardware config menu puts you back in main menu.
> Menu up no longer goes home

- ui.cpp
I'm not sure what is the source of the "clicks" in the first place. Probably synchronization between cores, are flash access. Might be good to investigate in the future.
> Audio cliks in recall screen fix

- rx.cpp
- rx.h
- rx_dsp.cpp
- rx_dsp.h
- ui.cpp
- ui.h
Scanning - memory and frequency:
- the scanners now pauses when a signal breaks the squelch threshold.
- Overlay a bar on the vertical S-meter to show the squelch level
- Updates display to show listen vs scanning
- move the rotary left or right to continue
- short press on "menu" -> launches scanner_radio_menu() with a subset of the main menu for quicker access 
- long press on menu -> select station and quit
- any press back -> quit and restore radio settings
TODO:
only resume scanning if no signal for > 'n' seconds
Behind the scenes:
- Expose squelch state so the scanner can use it
- factored out draw_vertical_dBm( 124, power_dBm);
- created dBm_to_63px(float power_dBm);
> Scanner now pauses when a signal is found

- ui.cpp
- ui.h
Wait 3 seconds of no sound before resuming scanning.
Using the rotary to continue scanning will set the scan direction based on which way you rotate it.
rewrote the (frequency) scanning logic as it was getting crazy
> Scanner waits for 3 seconds of < squelch level  before continuing

- CMakeLists.txt
- button_decoder.c
- button_decoder.h
- event.c
- event.h
- picorx.cpp
- ui.cpp
- ui.h
Another PR in the series. Now:
- the button events decoding is moved from `ui.cpp`
- events are now properly serialized, so the state logic can be simpler (no need for checking conjunctions of events)
- more sophisticated event decoding is possible, e.g. now pressing the encoder button two times quickly mutes and unmutes
> Further buttons handling refactor

- picorx.cpp
- rx.cpp
- rx_definitions.h
- rx_dsp.cpp
- simulations/am_sync_des.py
- simulations/deemphasis.py
- usb_audio_device.h
The software interpolated samplerate turned out to be problematic, especially when streaming USB audio from core0. This PR disables the interpolation and switches to 15ksps audio samplerate (+fixes and adjusts few minor things).
> Switched to fixed 15k samplerate

- ui.cpp
Setting the encoder resolution immediately was causing a "feedback effect". Switching the encoder to `High` resolution results in generating 2 encoder "ticks", which will constant toggling between `Low` and `High`. This PR breaks the feedback.
> Fixed "UI feedback" problem when setting encoder resolution

- button.cpp
- button.h
- picorx.cpp
- ui.cpp
- ui.h
We were occasionally missing button presses. The main problem was that button decoding was being made with the frequency of the UI update which is 10Hz, so 100ms. This is a little bit too slow for button decoding. This PR separates the button decoding rate from the UI update rate and increases it to 20Hz (50ms). As a bonus the button decoding logic became a little simpler (I think) and "button hold" detection is now a little bit faster.
> Button handling adjustments

- CMakeLists.txt
- button_encoder.cpp
- button_encoder.h
- ui.cpp
- ui.h
and some CMakeLists.txt cleanups
The button encoder driver can be enabled by adding `-DBUTTON_ENCODER=1` to cmake command.
> Added button encoder driver

- CMakeLists.txt
- pwm_audio_sink.cpp
- pwm_audio_sink.h
- rx.cpp
- rx.h
Factored-out the PWM sound output code and introduced some changes:
- slow ramping up and down of audio while tuning is removed - the clicking is only minor (different small countermeasure was implemented). Tuning is now faster without cutting-out of audio.
- synchronization with the PWM DMA is now explicit. Previously there was a chance that some PWM samples could be lost.
- the code is a little bit more decoupled and it will be easier to add more features in the future.
> Separated the PWM sound output/sink code

- rx_dsp.cpp
- simulations/am_sync_des.py
Not much increase computing power, but should perform even better than the previous PLL. Also lowered the loop bandwidth. 3rd-order loop is effectively a FLL (Frequency Locked Loop), can track continuous changes in frequency. Here is a plot of phase error when input changes frequency linearly:
3rd-order PLL has no lag an locks faster.
> Added 3rd-order PLL in synchronous AM demodulator

- rx_dsp.cpp
The differences between sound/silence are better visible this way + there is already AGC.
> Don't scale the waveform here. 

- CMakeLists.txt
Typo fix for the Pico2 variant of the build
> Pico2 Build Failure Fix
