ssd1306.c
I would like to use bigger, 1.3 inch OLED display and those displays are mostly based on SH1106 controllers, which are mostly compatible with the SSD1306 controllers, but don't support currently used addressing mode. This different addressing mode requires additional buffer, but I think it's worth it.
BTW, I've tested the u8g2 library with those I2C OLED displays on RP2040. Integrating this library would allow for many more displays being supported and more fancy UI would be possible. Let me know what you think. I have some spare cycles, so would be able to work on this.
=>  Changed the display memory addressing mode to be able to support different display controllers

rx.h, ssd1306.c, ssd1306.h, ui.cpp, ui.h
=> Added menu to select ssd1306 or sh1106

ui.cpp, ui.h
Can now set band start and stop (min and max frequency) #43 
ui::store can now edit the existing name
added clear option to clear all existing characters
=> edit band stop/start and modify existing memory name

ui.cpp, ui.h
Store can now delete a memory
added display_draw_separator(uint16_t y, uint32_t scale=1, bool colour=1); to draw either 1px, 2px or 3px separator
added display_get_x and display_get_y
added display_clear_str(uint32_t scale, bool colour); to  clears current line of text, cursor pos is unchanged
removed display_line1 and line2
other bits of tidying
=> store can delete and various tidying

rx.h, ui.cpp, ui.h
Added oled contrast adjustment
Fix bug in print_enum_option re: 2 option string length checking
=> Contrast setting and unrelated bugfix (take 2)

ui.cpp
sorry! I never actually plugged the headphones in.... it all _looked_ fine :(
=> Menu up no longer goes home... and now actually applies the changes to the radio

rx_definitions.h, rx_dsp.cpp, ui.cpp, ui.h
Might require more tuning, but even now it seems to reduce "whistles" and intelligibility of speech in low signal conditions.
=> First stab at synchronous AM demodulation

rx_dsp.cpp, simulations/am_sync_des.py
Some changes to the synchronous AM demodulator. Might be somewhat less efficient (still unnoticeable CPU load increase), but now I have somewhat more confidence regarding the fixed point scaling. Also added a Python script to (try to) prove that the PLL works.
=> Changed the fixed point scaling

ui.cpp, ui.h
Analog meter:
- refuses to draw height=0 (rather than crash with DIV0)
- can draw a rectangular style (specify negative height)
- now supports >180 degree faces
- Misc tidying of code, remove debugging printf
=> Analog meter widget fiddling

rx.cpp, rx_dsp.cpp, usb_audio_device.h
Slight adjustments to SR are fairly easy, so I decided to "bump" the samplerate from 15625 to round 16k.
=> Added interpolation to 16kHz

picorx.cpp, ui.cpp, ui.h
Rotating encoder while pressing now controls the volume.
=> Make volume controllable via encoder

picorx.cpp, ui.cpp
=> Further small button handling adjustments and

ui.cpp
Fix scanner button logic to 
a) work again :) 
b) benefit from the short/long logic rather than my own
=> Fix scanner button logic after recent event improvements

button_decoder.c, button_decoder.h, event.h, picorx.cpp, ui.cpp, ui.h
and some other minor adjustments.
=> Moved encoder to the rest of the events

rx_dsp.cpp
Sorry, just noticed my critical section was inside the loop....
=> Save 4% on cpu load (after removing my stupidity)

tusb_config.h, usb_audio_device.h, usb_descriptors.c
Small cleanup and unique USB serial number generation.
=> Just some small USB adjustments

fft_filter.cpp, fft_filter.h, rx.cpp, rx.h, rx_dsp.cpp, rx_dsp.h, ui.cpp, ui.h
This is the initial base of the functionality. Let me know if the choice I made are problematic. Here are some videos from testing using CubicSDR and GNU Radio:
https://github.com/user-attachments/assets/f95afe14-272c-487f-b57c-44ed643e408c
https://github.com/user-attachments/assets/9b599630-bc4a-4c6f-a179-a3d97ddca823
Adding AGC to the IQ samples would probably be a good idea.
=> IQ raw data streaming over USB

rx_dsp.cpp
Seems to be working okay, but may require some tuning, or exposing config values:
https://github.com/user-attachments/assets/4b058cf0-8a51-4fb4-a24f-eedede2d2cf4
=> Added AGC to the IQ stream

rx.cpp
=> Small DMA fix

CMakeLists.txt, encoder.h, rotary_encoder.cpp, rotary_encoder.h, ui.cpp, ui.h
I would like to add a "button-simulated" encoder and this PR is the first step to that.
=> Refactored (separated) the encoder

rx_dsp.cpp, rx_dsp.h, simulations/mag_estimator.py, utils.cpp
New estimator with better precision and moderate computational power demands. The precision vs speed can be easily controlled/adjusted. Here is a comparison plot:
and a zoomed version:
=> Added CORDIC-based magnitude estimator

rx.cpp, rx.h, rx_dsp.cpp, rx_dsp.h, simulations/audio_filters_des.py, ui.cpp, ui.h
Added basic bass (boost) and treble control. Works like a simple equalizer. Four levels of each:
=> Added basic bass and treble control

rx_dsp.cpp, simulations/am_sync_des.py
I managed to re-design the PLL and decrease the loop filter bandwidth. Now it tunes slower (can be heard), but should also sustain longer carrier disturbances. The effect is similar to other SDR software now (e.g. Gqrx).
=> Synchronous AM PLL update

rx_dsp.cpp
Needs to be from -pi to +pi not from -2pi to +2pi
=> Fixed phase wrapping

rx.cpp, rx_dsp.cpp, rx_dsp.h
Sometimes the demodulator got stuck in some strange state, so reset it after re-tune.
=> Added synchronous demodulator state resetting

rx.cpp, rx.h, rx_dsp.cpp, rx_dsp.h, settings.cpp, settings.h, ui.cpp
I was testing an impulse noise filter/blanker and the end result turned out to be fairly good, so here is the PR. Here is a plot from a sample recording:
Perceived audio effect is subtle. Sometimes AGC increases gain after enabling.
=> Added simple impulse noise blanker
